# -*- coding: utf-8 -*-
"""ZainabkhanML_Algorithms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hdOPvebsSK1cwe3YPIf6yMzWRdqcxV34
"""

#SVM_breastcancerdataset
from sklearn.datasets import load_breast_cancer
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load data
data = load_breast_cancer()
X, y = data.data, data.target

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Train model
svm = SVC()
svm.fit(X_train, y_train)

# Predict
y_pred = svm.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))