# -*- coding: utf-8 -*-
"""ZainabkhanML_Algorithms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hdOPvebsSK1cwe3YPIf6yMzWRdqcxV34
"""

#Decision_Tree

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

# Load dataset
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

# Preprocess
df = df[['Pclass', 'Sex', 'Age', 'Survived']].dropna()
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])

X = df[['Pclass', 'Sex', 'Age']]
y = df['Survived']

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Train
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

# Predict & output
pred = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, pred))