# -*- coding: utf-8 -*-
"""ZainabkhanML_Algorithms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hdOPvebsSK1cwe3YPIf6yMzWRdqcxV34
"""

#Logistic_Regression
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load dataset
iris = load_iris()
X, y = iris.data, iris.target

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Model training
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

# Prediction & Output
predictions = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, predictions))

